title: Zach Dyer Design
email: zach.dyer@zachdyerdesign.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to DyerDev, a passionate and skilled software development team with a knack for creating sleek, modern websites that prioritize both aesthetics and functionality.
  We specialize in building lightweight, secure websites that load quickly and perform exceptionally well in search engine rankings. We have a strong understanding of the latest technologies and trends in web development, and are dedicated to staying up-to-date on the latest best practices in order to deliver the best possible product for our clients.
  Whether you need a new website built from scratch, or an existing site in need of an update, DyerDev has the skills and expertise to bring your vision to life. So if you're looking for a tech-savvy professional who can create stunning, high-performing websites that stand out in a crowded online landscape, look no further than DyerDev.
tagline: Transform your online presence with beautiful, fast, and secure websites crafted by DyerDev.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dyerdev.com" # the base hostname & protocol for your site, e.g. http://example.com
paginate: 3
paginate_path: "/blog/page:1"
pagination_layout: blog-home
tier: premium

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
